apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  mysql-username: {{ .Values.secrets.mysql.username | b64enc | quote }}
  mysql-password: {{ .Values.secrets.mysql.password | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}