apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth2-credentials
type: Opaque
data:
  google-client-id: {{ .Values.env.googleClientId | b64enc | quote }}
  google-client-secret: {{ .Values.env.googleClientSecret | b64enc | quote }}