apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-oauth2
  labels:
    app: spring-boot-oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-oauth2
  template:
    metadata:
      labels:
        app: spring-boot-oauth2
    spec:
      containers:
      - name: spring-boot-oauth2
        image: axelav95/spring-boot-oauth2-google:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-credentials
              key: google-client-id
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-credentials
              key: google-client-secret