apiVersion: v1
kind: Service
metadata:
  name: spring-boot-oauth2-service
  labels:
    app: spring-boot-oauth2
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-oauth2
  type: LoadBalancer