apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: cm9vdA==  # base64 encoded "root"
  password: eW91cl9wYXNzd29yZA==  # base64 encoded "your_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: eW91ci12ZXJ5LXNlY3VyZS1zZWNyZXQta2V5LXBsZWFzZS1jaGFuZ2UtdGhpcw==  # base64 encoded secret